OrdererOrgs:

  - Name: Orderer
    Domain: regnet.reg
    Specs:
      - Hostname: orderer
      
PeerOrgs:

  - Name: Org1
    Domain: org1.regnet.reg
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org2
    Domain: org2.regnet.reg
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Org3
    Domain: org3.regnet.reg
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1 
