
version: '2'

volumes:
  orderer.regnet.reg:
  peer0.org1.regnet.reg:
  peer1.org1.regnet.reg:
  peer0.org2.regnet.reg:
  peer1.org2.regnet.reg:

networks:
  byfn:

services:

  orderer.regnet.reg:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.regnet.reg
    container_name: orderer.regnet.reg
    networks:
      - byfn

  peer0.org1.regnet.reg:
    container_name: peer0.org1.regnet.reg
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org1.regnet.reg
    networks:
      - byfn

  peer1.org1.regnet.reg:
    container_name: peer1.org1.regnet.reg
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org1.regnet.reg
    networks:
      - byfn

  peer0.org2.regnet.reg:
    container_name: peer0.org2.regnet.reg
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.regnet.reg
    networks:
      - byfn

  peer1.org2.regnet.reg:
    container_name: peer1.org2.regnet.reg
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.regnet.reg
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.regnet.reg:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.regnet.reg/peers/peer0.org1.regnet.reg/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.regnet.reg/peers/peer0.org1.regnet.reg/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.regnet.reg/peers/peer0.org1.regnet.reg/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.regnet.reg/users/Admin@org1.regnet.reg/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.regnet.reg
      - peer0.org1.regnet.reg
      - peer1.org1.regnet.reg
      - peer0.org2.regnet.reg
      - peer1.org2.regnet.reg
    networks:
      - byfn
